### ISSUE TITLE
Turn off auto-account onboarding for new users

### ISSUE THREAD

**Issue by rayi113** [heliumdatacommons/commonsshare#1]
Per the NIH Data Commons use cases, we are required to disable CommonsShare default of auto-account onboarding.  A different workflow should be implemented requiring a human-in-the-loop for new account approval on CommonsShare.

**Comment by hyi** [comment]
@rayi113 @clarisca When demoing CommonsShare user model refactoring last Friday, Ashok brought up this issue during the demo. As currently being implemented, anybody who can sign in through globus identify provider will be able to sign in to CommonsShare, which is most likely not desired. Should we implement human-in-the-loop user activation/approval process into CommonsShare within the first 6 months? If so, I'll create an issue for this and work on it. I think we can send the administrator email upon a user signing in for the first time, and administrator has to click on a link from the email to activate the user. We will have to think through the management burden, though, and how practical it is to add this human-in-the-loop user approval process.

**Comment by rayi113** [comment]
@hyi @clarisca Related to this, what is emerging in KC6 is to create a white list of approved people rather than a human-in-the-loop approval.  Could you implement a white list of approved people?  Right now the white list can be local, but eventually it may be centralized.  Mention: @theferrit32

**Comment by theferrit32** [comment]
@rayi113 @hyi if it just a single white-list across all datasets then I think this can be handled entirely by CommonsShare.  Once my token service redirects back to CommonsShare with an openid access token, and CommonsShare fetches the profile information from Globus, it can check to see if the email address matches one from a predetermined white-list.  This will still grant everyone the same data access once they've successfully created an account in CommonsShare.  

If there are going to be separate white-lists for different datasets which contain different sets of identities, then the permissions handling should probably be moved down into iRODS ACLs on the parent directories of each dataset.

**Comment by hyi** [comment]
@rayi113 Agreed with @theferrit32. Let me create an issue for adding this white-list of approved users in the process of signing in users via globus in CommonsShare. For data registration and access, I agree with @theferrit32 that everyone (who is white-listed and signed in successfully in CommonsShare) should be subject to the same data access permissions.
