### ISSUE TITLE
Globus authenticaion not work

### ISSUE THREAD

**Issue by amalic** [heliumdatacommons/commonsshare#25]
I signed up for a Globus Id to be able to login to commonsshare.

After some clicking around on commons-share I suddenly was logged out and am not more able to login via my Globus Id. When I try to login i only have the option to enter a username and password.

**Comment by rayi113** [comment]
Please use: https://beta.commonsshare.org/   (i.e. don't use https://www.commonsshare.org/, it's a placeholder for an eventual production version of CommonsShare, but currently contains deprecated code).
